# Docker Compose Version
version: "3.8"

# Pay attention to Service execution order since it matters
# Loading up each service will be dependant on one or another sometimes
# To deal with this you can either set depends_on, or you can also
# establish a good execution order for the services to spin up.
# This is important if using technology such as Docker Swarm,
# as currently the depends_on is ignored.

# Images are chosen instead of using latest tag to provide stability

# MySQL Database
services:
  db:
    image: mysql:8.0.27
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: test1
      MYSQL_DATABASE:
      MYSQL_USER: kxtran
      MYSQL_PASSWORD: test

  # Apache & PHP built through Dockerfile in ./web folder
  web:
    build: ./web
    container_name: web
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html/
    ports:
      - 8080:80
    networks:
      - frontend
      - backend

  # Database Management
  # Adminer Database Management Software
  dbms:
    image: adminer
    container_name: dmbs
    depends_on:
      - db
    restart: always
    networks:
      - backend
    ports:
      - 8081:8080

# Networks to compartmentalize
networks:
  frontend:
  backend:
